base/urls.py
from django.urls import path
from . import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('compra_finalizada/', views.finalizar_compra, name='compra-finalizada'),
    
]

pedidos/urls.py
from django.urls import path 
from . import views

app_name='pedidos'

urlpatterns = [
    path('', views.pedido, name='pedido')
]

pedidos/models.py
from django.db import models
from productos.models import Producto
from django.contrib.auth.models import User

class Pedido(models.Model):
    ESTADOS_CHOICES = (
        ('en_proceso', 'En preceso'),
        ('enviado', 'Enviado'),
        ('entregado', 'Entregado'),
        ('cancelado', 'Cancelado')
        
    )
    
    METODO_CHOICES = (
        ('efectivo', 'Efectivo'),
        ('tarjeta_credito', 'Tarjeta Credito'),
        ('tarjeta_debito', 'Tarjeta Debito'),
        ('paypal', 'Paypal')
    )
    cliente = models.ForeignKey(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto)
    estado = models.CharField(max_length=20, choices=ESTADOS_CHOICES, default='en_proceso')
    metodo_pago = models.CharField(max_length=20, choices=METODO_CHOICES)
   # total = modelds.
    created = models.DateTimeField(auto_now_add=True) 
       
       
    def __str__(self):
        return f'Pedido #{self.id}'

pedidos/views.py
from django.shortcuts import render
from carrito.carrito import Carro
from .models import Pedido
from django.core.mail import send_mail
from core import settings
from django.template.loader import render_to_string

#importamos para renderizar archivo html con jinja
from django.template import engines

def pedido(request):
    
    #le pasamos nuevamente la variable total porque no es global, deberiamos optimizar eso
    #con el contextprocessor
    carro = Carro(request)
    total = carro.obtener_total()
    
    #print(total)
    if request.method == 'GET':
        #creamos nuestro pedido usando Pedido.objects.create para guardarlo en la base de datos
        
        return render(request, 'pedidos.html',{
            'total':total
        })
        
#creamos una funcion que reciba el request y lo usamos en la url de finalizar compra
def email_pedido(request):

    lista = []
    carro = Carro(request)
 
    # Iteramos sobre cada elemento del carro, aunque seria mejor guardar cada valor en un diccionario
    for fruta in carro.carro.items():
       #print(fruta[1]['nombre'])
        fruta_pedido = (fruta[1]['nombre'], fruta[1]['cantidad'])
        lista.append(fruta_pedido)
    
    print('Email enviado')
    total = carro.obtener_total()
    
    #abrimos nuestro html para enviar los datos del pedido realizado
    #with open('pedidos/templates/pedido_email.html', 'r') as archivo:
    
    #    html_message2 = archivo.read()
    html_content = render_to_string('ticket/pedido_email.html')
    
    
    #si enviamos un html_message el messge se ignora automaticamente. No se envia al email
    send_mail(
        subject="Compra Finalizada",
        message=f"Gracias por su compra en Verdulería MA: {lista}\nTotal:{total}", #queda ignorado
        html_message= html_content,
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email],
        fail_silently=False,
    )
    

pedidos/templates/pedido_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>Pedido realizado</h1>

    <table>
        <thead>
            <tr>
                <th>Fruta</th>
                <th>Cantidad</th>
            </tr>
        </thead>

        <tbody>
            {% for fruta in lista %}
                <tr>
                    <td>{{ fruta.0 }}</td>
                    <td>{{ fruta.1 }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

</body>
</html>

pedidos/templates/pedido_email2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>Pedido realizado</h1>

    <table>
        <thead>
            <tr>
                <th>Fruta</th>
                <th>Cantidad</th>
            </tr>
        </thead>

        <tbody>
            {% for fruta in lista %}
                <tr>
                    <td>{{ fruta.0 }}</td>
                    <td>{{ fruta.1 }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

</body>
</html>

pedidos/templates/pedidos.html
{% extends 'base.html' %}

{% block title %}Pedido{% endblock %}


{% block content %}
    <h1>Pedidos de {{user.username}} </h1>

    <div class="container" style="max-width: 500px;">
       <table class="table table-striped-columns tablaconfig">
           <thead>
               <tr>
                   <th>#</th>
                   <th>Producto</th>
                   <th>Cantidad</th>
                   <th>Precio</th>
               </tr>
           </thead>
           <tbody>
               {% for key, value in request.session.carro.items %}
                   <tr>
                       <td>{{forloop.counter}} </td>
                       <td>{{value.nombre}} </td>
                     
                       <td>{{value.cantidad}} </td>
    
                       <td>{{value.precio}} </td>
                   </tr>
               {% endfor %}
               <tr class="text-end">
                   <td colspan="4">Total: {{total}} </td>
               </tr>


           </tbody>
       </table>

       <div class="container text-center">
        
            <a href="{% url 'inicio:compra-finalizada' %}" class="btn btn-danger btn-lg btn-block">Finalizar Comprar </a>
     
       </div>
 
    
    </div>


{% endblock %}