base/urls.py
from django.urls import path
from . import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('compra_finalizada/', views.finalizar_compra, name='compra-finalizada'),
    
]

tienda/urls.py
from django.urls import path
from . import views

app_name = 'tienda'

urlpatterns = [
    path('', views.tienda, name='tienda'),
    path('agregar_producto/<int:producto_id>', views.agregar_producto, name='agregar-producto'),
    path('restar_producto/<int:producto_id>', views.restar_producto, name='restar-producto'),
    path('vaciar_carrito/', views.vaciar_carrito, name='vaciar-carrito'),
    
    
    
]

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('registro/', views.registro, name='registro'),
    path('inicio-sesion/', views.inicio_sesion, name='inicio-sesion'),
    path('cerrar-sesion/', views.cerrar_sesion, name='cerrar-sesion')
    
    
]

base/views.py
from django.shortcuts import render
from contacto.forms import ContactoForm
from django.core.mail import send_mail
from core import settings
from carrito.carrito import Carro
from pedidos.views import email_pedido
from productos.models import Producto

def inicio(request):
    
    # Formulario de Contacto
    form = ContactoForm()
    
    # Obtenemos todos los productos con oferta
    productos = Producto.objects.filter(oferta=True)
    
    # Iniciamos pagina
    if request.method == 'GET':
        return render(request, 'inicio.html', {
            'form':form,
            'productos':productos
        })
        
    #recibimos el form
    elif request.method == 'POST':
        form_request = ContactoForm(request.POST)
        
        if form_request.is_valid():
            email = form_request.cleaned_data['email']
            asunto = form_request.cleaned_data['asunto']
            mensaje = form_request.cleaned_data['mensaje']
            
            mensaje = f"Email de: {email} \nMensaje: {mensaje}"
            
            send_mail(
                subject=asunto,
                message=mensaje,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=['leoulirodriguez@gmail.com'],
                fail_silently=False,
            )
            
            return render(request, 'inicio.html',{
                'mensaje':"Correo enviado correctamente!",
                'form':form
            })
            
def finalizar_compra(request):
    form = ContactoForm()
    carro = Carro(request)
    
    if request.method == 'GET':
                
        #enviamos un mail con todo lo que tiene a una direccion de email
        email_pedido(request)
        
        #vaciamos carrito despues de enviar los datos con el request
        carro.vaciar_carrito()

        return render(request, 'inicio.html',{
            'mensaje':"Gracias por su compra",
            'form':form
        })

base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %} </title>

    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

    <!-- NAVBAR -->
    
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <img src="{% static 'imagenes/logo-manzana.png' %}" alt="Logo imagen" class="logo">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'inicio:inicio' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tienda:tienda' %}">Productos</a>
              </li>
              {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'usuarios:cerrar-sesion' %}">Cerrar Sesion</a>
                </li>
              {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'usuarios:inicio-sesion' %}">Iniciar Sesion</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'usuarios:registro' %}">Registrarse</a>
                </li>
              {% endif %}

            </ul>
          </div>
        </div>
      </nav>
    
    <!-- CONTENT -->
    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

base/templates/home.html
{% extends 'base.html' %}

{% block title %} Inicio {% endblock %}

{% block content %}
    <h1>Inicio</h1>
{% endblock %}

base/templates/inicio.html
{% extends 'base.html' %}

{% load static %}
{% block title %} Inicio {% endblock %}

{% block content %}
    <h1 class="inicio h1-shadow">Inicio</h1>
    
    {% if mensaje %}
      <div class="alert alert-success" role="alert">
        {{mensaje}}
      </div>
    {% endif %}

    
    <div class="midiv">
      
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br> <br>

        <!-- CARRUSEL -->
        <div id="carouselExampleAutoplaying" class="carousel slide carusel" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{% static 'imagenes/durazno.jpg' %}" class="d-block w-100 img-fluid" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{% static 'imagenes/naranja.jpg' %}" class="d-block w-100 img-fluid" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{% static 'imagenes/uva.jpg' %}" class="d-block w-100 img-fluid" alt="...">
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
          <br>

          <!-- OFERTAS -->
          <div class="container">
            <h1>OFERTAS</h1>
              <div class="container">
                <div class="row" style="max-width: 800px; margin: 0 auto;">
                    {% for producto in productos %}
                    <div class="col-4">
        
                        <div class="card text-center card-fruta" style="width: 12rem;">
                            <img src="{{producto.imagen.url}}" class="card-img-top" alt="imagen de producto">
                            <div class="card-body">
                              <h5 class="card-title">{{producto.nombre}}</h5>
                              <p class="card-text">{{producto.categoria}} </p>
                              <a href="{% url 'tienda:agregar-producto' producto.id %}" class="btn btn-success">Comprar
                                  <i class="bi bi-cart-plus"></i>
                              </a>
                              <button class="btn btn-danger position-absolute top-0 start-0 m-3">OFERTA</button>
                            </div>
                        </div>
        
                    </div>
                    
                    {% endfor %}
            
                </div>
              </div>
          </div>

          <!-- CONTACTO -->
          <div class="container contenedor-contacto">
            <div class="d-grid gap-2 contacto">
              <div class="badge text-bg-primary div-contacto">
                Contacto
              </div>
            </div>

            <form action="" method="POST">
              {% csrf_token %}
              {{form.as_p}}

              <button class="btn btn-primary">Enviar</button>
            </form>
          </div>
    
        
    </div>

    <div class="contenedor-titulo"> 
       
            <h2 class="titulo-cont">
                <span class="border border-end-0 border-4 borde-titulo">
                    Verduleria MA
                </span>
            </h2>
      
    </div>
     <br><br><br>

     
    
    
{% endblock %}