base/urls.py
from django.urls import path
from . import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('compra_finalizada/', views.finalizar_compra, name='compra-finalizada'),
    
]

carrito/urls.py
from django.urls import path
from . import views
"""
app_name = 'carrito'

urlpatterns = [
    path('agregar/<int:id_producto>', views.agregar_carrito, name='agregar'),
    path('ver_carrito/', views.ver_carrito, name='ver_carrito'),
      
]"""

pedidos/urls.py
from django.urls import path 
from . import views

app_name='pedidos'

urlpatterns = [
    path('', views.pedido, name='pedido')
]

tienda/urls.py
from django.urls import path
from . import views

app_name = 'tienda'

urlpatterns = [
    path('', views.tienda, name='tienda'),
    path('agregar_producto/<int:producto_id>', views.agregar_producto, name='agregar-producto'),
    path('restar_producto/<int:producto_id>', views.restar_producto, name='restar-producto'),
    path('vaciar_carrito/', views.vaciar_carrito, name='vaciar-carrito'),
    
    
    
]

carrito/models.py
from django.db import models

    

carrito/views.py
from django.shortcuts import render, get_object_or_404, redirect
from productos.models import Producto
from .carrito import Carro

"""
def agregar_carrito(request, id_producto):
    
    #buscamos el producto que le enviamos por url
    producto = get_object_or_404(Producto, pk = id_producto)
    carrito = Carro(request)
    #agregamos ese producto al carrito
    carrito.agregar_producto(producto)
    return redirect('productos:productos')

def ver_carrito(request):
    
    carrito = Carro(request)
    total = carrito.obtener_total()
    #print(total)
    if request.method == 'GET':
        
        return render(request, 'ver_carrito.html',{
            'carrito':carrito,
            'total':total
        })
"""
    
    

carrito/templates/ver_carrito.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Carrito de {{user.username}}</h1>

    Total: {{total}}
    {% for item in carrito.carro %}
        {{item}}
        
    {% endfor %}

    {% for key, value in request.session.carro.items %}
    
        {{value.nombre}}
    {% endfor %}
</body>
</html>

carrito/templates/widget-carrito.html
<!-- <div class="container">
    <div class="row">
        <div class="col-8">
            <h1>Compra de {{user.username}}</h1>
        </div>
        <div class="col-4">
            <i class="bi bi-cart carrito"></i>
        </div>
   
    </div> -->

<div class="container">
    
    <h1>Compra de {{user.username}}  <i class="bi bi-cart carrito"></i>  <i class="bi bi-hdd-stack-fill"></i> </h1>

    <table class="table table-striped-columns tablaconfig">
        <thead>
            <tr>
                <th>#</th>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Precio</th>
            </tr>
        </thead>
        <tbody>
            {% for key, value in request.session.carro.items %}
                <tr>
                    <td>{{forloop.counter}} </td>
                    <td>{{value.nombre}} </td>
                  
                    <td>{{value.cantidad}} </td>
 
                    <td>{{value.precio}} </td>
                </tr>
            {% endfor %}
            <tr class="text-end">
                <td colspan="4">Total: {{total}} </td>
            </tr>
        </tbody>
    </table>

    {% if request.session.carro.items %}


        <div class="container">
            <div class="row">
                <div class="col text-end">
                  <a href="{% url 'tienda:vaciar-carrito' %}">
                    <button class="btn btn-danger">
                        VACIAR CARRITO
                    </button>
                  </a>
                </div>
                <div class="col text-start">                      
                  <a href="{% url 'pedidos:pedido' %}" >
                    <button class="btn btn-success boton-completar">
                        COMPRAR
                    </button>
                  </a>
                </div>
            </div>

        </div>

        <div class="">
     
            
      
            </div>
 
        </div>

  
    {% endif %}


</div>